### ISSUE TITLE
Understanding of JSON output

### ISSUE THREAD

**Issue by rplCloud** [rtfd/CommonMark-py#76] opened 2016-07-05 08:36 UTC
Hi all,

I try to get JSON output using this library.

I tried the Python library and the cmark command line tool with the same results. HTML and AST looks ok for me:

```bash
cmark  <<< '*hello!*'
```
```html
<p><em>hello!</em></p>
```
```bash
cmark -a <<< '*hello!*'
```
```
[document]
	Title:
	Info:
	Destination:
	Sourcepos: [[1, 1], [1, 8]]
	Info:
	Literal:
	Children:
		-> [document]
			-> Title:
			-> Info:
...
```

But I do not understand the JSON output:

```bash
cmark -aj <<< '*hello!*'
```
```json
{"is_fenced": false, "t": "document", "sourcepos": [[1, 1], [1, 8]], "fence_length": 0, "open": false, "last_line_blank": false}
```

Honestly, I have no idea what this all about...

I expect some like this:

```json
[ "paragraph" , [
  [ "emph" , {} , [
    [ "text" , {} , [ "hello"
...
```

Can you give me some hints what I am oing wrong?

Regards,
Reto

**Comment by nikolas** [comment] 2016-07-19 13:04
It looks like it's printing out the internal structure for the Node class. See https://github.com/jgm/commonmark.js/blob/master/lib/node.js#L70

We could change this to be more user-friendly.

**Comment by nikolas** [comment] 2016-07-19 20:26
After reproducing the problem, it looks like the [ASTtoJSON](https://github.com/rtfd/CommonMark-py/blob/master/CommonMark/main.py#L66) function is broken. I will look into it. Thanks for letting me know.

**Comment by nikolas** [comment] 2016-07-20 01:12
I've come up with a fix and made a pull request, which will get merged soon.

**Closed** 2016-07-20 15:20 UTC
