### ISSUE TITLE
The wheel file distributed has a spurious path

### ISSUE THREAD

**Issue by yuhui-lin** [rtfd/CommonMark-py#59] opened 2016-04-02 21:16 UTC
I am using macbook.
$sudo -H pip install commonmark
```
  $cmark.py -h
  -bash: /usr/local/bin/cmark.py: /home/nnyby/src/CommonMark-py/venv/bin/python: bad interpreter: No such file or directory

**Comment by lu-zero** [comment] 2016-04-03 04:16
Check your python setup, looks like your venv is having problems.

**Comment by me-and** [comment] 2016-04-05 15:18
The problem has nothing to do with the Python setup or virtual environment – it's in the Wheel file on PyPI – if you [download it](https://pypi.python.org/packages/3.4/C/CommonMark/CommonMark-0.6.3-py2.py3-none-any.whl#md5=476acd845d4d66a2d4065ca0d604d8a9) and unpack it with your preferred zip file manager, you'll find that `/home/nnyby/src/...` line as the shebang in the packaged `cmark.py` file.

The error doesn't exist in this repository or the source package, so the problem is clearly creeping in during the wheel generation process.

As a work-around, you can tell `pip` to not use the wheel file and instead install from source as below:

    pip install --no-binary commonmark commonmark

That gets me a working install of the package.

**Comment by yuhui-lin** [comment] 2016-04-05 15:30
Thanks for your solution. @me-and . 
what I did is changing the first line of ``/usr/local/bin/cmark.py`` from ``#!/home/nnyby/src/CommonMark-py/venv/bin/python`` to ``#!/usr/bin/python``.
It looks stupid, but it fixed my problem.

**Comment by lu-zero** [comment] 2016-04-05 16:03
Let's keep it open and cc @nikolas

**Comment by nikolas** [comment] 2016-04-05 17:07
Oh jeeze... my home directory path shouldn't be in the wheel file! Obviously something is messed up here.. I will investigate and fix this evening. Thanks for letting me know.

I generated this wheel file in a virtualenv, running `./venv/bin/python setup.py sdist bdist_wheel`... I'll find out what I need to do differently.

**Comment by nikolas** [comment] 2016-04-07 04:26
It looks like this is a bug in wheel, the subunit project also ran into this problem, and opened this ticket: https://bitbucket.org/pypa/wheel/issues/135/bad-interpreter-lines-can-sneak-into

I'm still trying to figure out a way to fix our wheel file, though. I can't seem to find the right procedure of generating the wheel file that doesn't have the bad path in it.

**Comment by nikolas** [comment] 2016-06-01 18:55
This can be fixed by declaring the script via setup.py's entry_points attribute instead of in scripts. I've followed piprot's example: https://github.com/sesh/piprot/blob/master/setup.py#L26

I've just opened a pull request that should address this problem.

**Closed** 2016-06-03 17:30 UTC
